# AWS_ACCESS_KEY_ID: AKIAJFGW7TOOA3KA5FHQ
# AWS_SECRET_ACCESS_KEY: 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
# AWS_BUCKET: "hashoutbout"

GSTORAGE_HOST: http://kensphotouploads.commondatastorage.googleapis.com
GSTORAGE_BUCKET: kensphotouploads
GSTORAGE_ACCESS_KEY_ID: GOOGUL5WOE5QMSFQZKY5
GSTORAGE_SECRET_ACCESS_KEY: V7yjGuJovQXcFCv2BgT/D4aPnor74YZmE0nMhgrP