GSTORAGE_HOST: http://kensphotouploads.commondatastorage.googleapis.com
GSTORAGE_BUCKET: kensphotouploads
GSTORAGE_ACCESS_KEY_ID: GOOGUL5WOE5QMSFQZKY5
GSTORAGE_SECRET_ACCESS_KEY: V7yjGuJovQXcFCv2BgT/D4aPnor74YZmE0nMhgrP